<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AddDataFromFile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>57d0ce3b-a313-421f-ac51-f8944127c6e7</testSuiteGuid>
   <testCaseLink>
      <guid>47c88212-8794-4572-9c97-a2d524da28b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_009_lab8_addDataFromFile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>33c557ce-cfd9-42b9-83e8-97efd523fa50</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dataLogin</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>33c557ce-cfd9-42b9-83e8-97efd523fa50</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2c820b2b-99a9-4a1e-b6e4-48f2f2a844a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33c557ce-cfd9-42b9-83e8-97efd523fa50</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>4fccfd4e-e85b-4414-a321-eb0f806c3f40</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
